name: Run tests

on:
  workflow_dispatch:
  push:
    paths:
    - 'src'
    - 'tests'
    - '**.toml'
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  CodeQL-Analysis:
    runs-on: ubuntu-latest
    permissions:
      security-events: write # required for all workflows
      # only required for workflows in private repositories:
      actions: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: python

      # Autobuild attempts to build any compiled languages (C/C++, C#, Go, or Java).
      # If this step fails, then you should remove it and run the build manually
      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2


  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ "{{" }} matrix.python-version {{ "}}" }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ "{{" }} matrix.python-version {{ "}}" }}

    - name: Install dependencies
      run: |
        pip install ".[test,dev, train]"

    - name: Test with pytest
      run: |
        pytest --cov=src --cov-report=term-missing tests